Sesion_03/movies/urls.py
"""Movies app URls"""

from django.urls import path

from .views import list_movies, add_movie

app_name = 'movies'
urlpatterns = [
    path("", list_movies, name="list"),
    path("add", add_movie, name="add"),
]

Sesion_03/music/urls.py
"""Music app URls"""

from django.urls import path

from .views import list_songs, create_song, song_detail

app_name = 'music'
urlpatterns = [
    path("", list_songs, name="list"),
    path("create", create_song, name="create"),
    path("detail/<int:pk>", song_detail, name="detail")
]

Sesion_03/spotify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    path('movies/', include('movies.urls')),
]

Sesion_03/movies/models.py
""" Movies app models """

from django.db import models

class Director(models.Model):
    """Writer Model"""
    # id = models.AutoField(primary_key=True) "Este campo no es necesario ponerlo en automativo Django lo crea."
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Year(models.Model):
    """ Year Model"""
    year = models.IntegerField()

    def ___str___(self):
        return str(self.year)

class Movie(models.Model):
    """ Movie Model """
    title = models.CharField(max_length=255)
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)  

    def __str__(self):
        return self.title

Sesion_03/music/models.py
""" Music app models """

from django.db import models

class Artist(models.Model):
    """Artist Model"""
    # id = models.AutoField(primary_key=True) "Este campo no es necesario ponerlo en automativo Django lo crea."
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Album(models.Model):
    """ Album Model"""
    title = models.CharField(max_length=255)
    # Creamos la llave foranea de la sigueinte forma.
    # on_delete es un protocolo que usamos CASCADE para eliminar todos Albums de ese artista.
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Song(models.Model):
    """ Song Model """
    title = models.CharField(max_length=255)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file = models.FileField(upload_to='music/')

    def __str__(self):
        return self.title

Sesion_03/movies/views.py
from django.shortcuts import render, redirect

from .models import Director, Movie, Year


def list_movies(request):
    """List all songs"""
    movies = Movie.objects.all().order_by('director__name', 'title')
    context = {"movies": movies}
    return render(request, 'movies/list_movie.html', context)


def add_movie(request):
    """Add a new movie"""
    if request.method == "POST":
        director_name = request.POST.get("director_name")
        movie_title = request.POST.get("movie_title")
        film_year = request.POST.get("film_year")
        director, _created = Director.objects.get_or_create(name=director_name)
        film_year, _created = Year.objects.get_or_create(year=film_year)
        movie = Movie(title=movie_title, director=director, year=film_year)
        movie.save()
        return redirect("movies:list")

    return render(request, 'movies/add_movie.html')

Sesion_03/music/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Song, Artist, Album


def list_songs(request):
    """List all songs"""
    songs = Song.objects.all().order_by('artist__name', 'title')
    context = {"songs": songs}
    return render(request, 'music/song_list.html', context)


def create_song(request):
    """Create a new song"""
    if request.method == "POST":
        song_title = request.POST.get("song_title")
        artist_name = request.POST.get("artist_name")
        album_title = request.POST.get("album_title")
        song_file = request.FILES.get("song_file")
        artist, _created = Artist.objects.get_or_create(name=artist_name)
        album, _created = Album.objects.get_or_create(title=album_title, artist=artist)
        song = Song(title=song_title, artist=artist, album=album, file=song_file)
        song.save()
        return redirect("music:list")

    return render(request, 'music/song_create.html')

def song_detail(request, pk):
    """ Shows a Song detail"""
    song = get_object_or_404(Song, pk=pk)
    song = Song.objects.get(pk=pk)
    return render(request, 'music/song_detail.html', {"song":song})

Sesion_03/movies/templates/movies/add_movie.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Add Movie</title>
</head>
<body>
  <h1>Add Movie</h1>

  <form method="post">
    {% csrf_token %}
    <p>
      <label for="movie-title">Título</label>
      <input type="text" name="movie_title" id="movie-title">
    </p>

    <p>
      <label for="writer-name">Director</label>
      <input type="text" name="director_name" id="director-name">
    </p>

    <p>
      <label for="film-year">Film Year</label>
      <input type="number" name="film_year" id="film-year">
    </p>

    <button type="submit">Agregar</button>
  </form>
</body>
</html>

Sesion_03/movies/templates/movies/list_movie.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Movie List</title>
</head>
<body>
  <h1>Movie List</h1>

  <ul>
    {% for movie in movies %}
      <li>
        {{ movie.title }} - {{ movie.director.name }} - {{ movie.year.year}}
      </li>
    {% endfor %}
  </ul>

</body>
</html>

Sesion_03/music/templates/music/song_create.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Crear</title>
</head>
<body>
  <h1>Crear canción</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
      <label for="song-title">Título</label>
      <input type="text" name="song_title" id="song-title">
    </p>

    <p>
      <label for="artist-name">Artista</label>
      <input type="text" name="artist_name" id="artist-name">
    </p>

    <p>
      <label for="album-title">Álbum</label>
      <input type="text" name="album_title" id="album-title">
    </p>

    <p>
      <label for="song-file">Álbum</label>
      <input type="file" name="song_file" id="song-file">
    </p>

    <button type="submit">Crear</button>
  </form>
</body>
</html>

Sesion_03/music/templates/music/song_detail.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Canción</title>
</head>
<body>
  <h1>{{song.title}}</h1>
  <p>{{ song.artist.name}}</p>
  <p>{{ song.album.title}}</p>

  <audio controls>
    <source src="{{ song.file.url }}" type="audio/mpeg">
    Tu navegador no soporta el elementro de audio
  </audio>
  <br>
  <a href="{% url 'music:create' %}">Crear Cancion</a>

</body>
</html>

Sesion_03/music/templates/music/song_list.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mis Canciones</title>
</head>
<body>
  <h1>Mis canciones</h1>

  <a href="{% url 'music:create' %}">Crear Cancion</a>

  <ul>
    {% for song in songs %}
      <li>
        {{ song.title }} - {{ song.artist.name }} - {{ song.album.title }}
        <br>
        <a href="{% url 'music:detail' song.pk %}">Ver Detalle</a>
      </li>
    {% endfor %}
  </ul>

</body>
</html>