Sesion_02/bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('food/', include('food.urls')),
]

Sesion_02/food/urls.py
"""Food app URL config"""

from django.urls import path

from .views import list_food, detail_food, create_food, lista_lenguajes, crear_lenguajes

app_name = 'food'
urlpatterns = [
    path('', list_food, name='list'),
    path('<int:id>', detail_food, name='detail'),
    path('create', create_food, name='create'),
    path('lenguajes', lista_lenguajes, name = 'lenguajes'),
    path('crearleng', crear_lenguajes, name='crear_leng'),
    
]

Sesion_02/food/views.py
"""Food App Views"""

import random
from django.shortcuts import render, redirect


name = ["Mauricio", "Luis", "Jorge", "Ximena", "Luis"]
food = ["Pizza", "Sushi", "Alitas", "Hamburguesa", "Costillas a la BBQ"]
lenguajes = ["C ++", "Javascript", "Python", "Ruby", "Scala", "Java"]
lenguajes_list = []

def list_food(request):
    context = {
        "name" : random.choice(name),
        "food" : food
    }

    return render(request, "list.html", context)

def detail_food(request, id):
    context = {
        "food" : food[int(id)]
    }
    return render(request, "detail.html", context)

def lista_lenguajes(request):
    context = {
        "lenguajes_list" : lenguajes
    }
    return render(request, "lenguajes.html", context)

def create_food(request):
    """Create a food"""
    if request.method == 'POST':
        name = request.POST['name']
        food.append(name)
        return redirect('food:list')
    return render(request, "create.html")

def crear_lenguajes(request):
    if request.method == 'POST':
        name = request.POST['name']
        lenguajes_list.append(name)
    ''' Siempre es importante crear el contexto para poder pasar la información que se quiere renderizar en la plantilla'''
    context = {
        "lenguajes": lenguajes_list,
        "lenguajes_list": lenguajes
    }
    return render(request, "crear_leng.html", context)

Sesion_02/food/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  {% block title %}
  <title class="title">App de Comida</title>
  {% endblock title %}
</head>
<body>
  {% block content %}{% endblock content %}
</body>
</html>

Sesion_02/food/templates/crear_leng.html
{% extends 'base.html' %}

{% block content %}
<h1>Agregar nuevo lenguaje</h1>

<form action="{% url 'food:crear_leng' %}" method="POST">
  {% csrf_token %}  <!--Siempre se debe poner por seguridad -->
  <p>
    <label for="name-id">Nombre:</label>
    <input type="text" name="name" id="name-id" />
  </p>
  <button type="submit">Crear</button>
</form>


<h1>Mi lista de lenguajes de programación</h1>
  {% if lenguajes %}
    <ul>
      {% for item in lenguajes %}
      <li>{{ item }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay Lenguajes</p>
  {% endif %}


<h1>Mi lista de lenguajes de programación</h1>
  {% if lenguajes_list %}
    <ul>
      {% for item in lenguajes_list %}
      <li>{{ item }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay Lenguajes</p>
  {% endif %}
  {% endblock content %}

Sesion_02/food/templates/create.html
{% extends 'base.html' %}

{% block content %}
<h1>Crear nuevo alimento</h1>

<form action="{% url 'food:create' %}" method="POST">
  {% csrf_token %}
  <p>
    <label for="name-id">Nombre:</label>
    <input type="text" name="name" id="name-id" />
  </p>
  <button type="submit">Crear</button>
</form>
{% endblock content %}

Sesion_02/food/templates/detail.html
{% extends "base.html" %}

{% block title %}
<title>Detalle de {{ food }}</title>
{% endblock %}

{% block content %}
<h1>Detalle de {{ food }}</h1>
{% endblock content %}

Sesion_02/food/templates/lenguajes.html
{% extends "base.html" %}

{% block content %}
<h1>Mi lista de lenguajes de programación</h1>
  {% if lenguajes_list %}
    <ul>
      {% for item in lenguajes_list %}
      <li>{{ item }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay Lenguajes</p>
  {% endif %}
{% endblock content %}

Sesion_02/food/templates/list.html
{% extends "base.html" %}

{% block content %}
<h1>Comida de {{ name }}</h1>
  {% if food %}
    <ul>
      {% for item in food %}
      <li>{{ item }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay comida</p>
  {% endif %}
{% endblock content %}